### ISSUE TITLE
Source tree contains generated binaries

### ISSUE THREAD

**Issue by lool** [Xilinx/mv-defect-detect#3]
Hi

Besides 10gige/libGigE, the binaries that are to be built by this tree are committed under https://github.com/Xilinx/mv-defect-detect/tree/xlnx_rel_v2022.1/10gige/application/Arm64/Release

Please only commit to your repo the binaries that won't be built by the build process.

Thanks!
LM

**Comment by karthikxil** [comment]
Hi Loic,

Removed gvrd binary which is generated as part of build. Addressed this comment in https://github.com/Xilinx/mv-defect-detect/commit/4ace522568e7b94e9d8f3aee5e35438ffc1974b3

Thanks,
Karthik
