### ISSUE TITLE
Two copies of start.sh

### ISSUE THREAD

**Issue by lool** [Xilinx/mv-defect-detect#5]
Hi,

There are two copies of start.sh; one under Release/, and one above. It looks like the one under Release is the most recently modified one, but I suspect only one of the two is needed and the other one should be dropped.

Also, you have a pre-built gvrd in the tree that IMO shouldn't be there as it's meant to be built.

Best
LM

**Comment by karthikxil** [comment]
Hi Loic,

Addressed this comment in https://github.com/Xilinx/mv-defect-detect/commit/4ace522568e7b94e9d8f3aee5e35438ffc1974b3

Thanks,
Karthik
