### ISSUE TITLE
Please fix permissions of *.bin

### ISSUE THREAD

**Issue by lool** [Xilinx/mv-defect-detect#6]
Hi,

I believe eeprom.bin and alloc_table.bin are just data; could you change their permissions in the git repo to drop the +x bit? It is triggering warnings during package builds:
W: xlnx-app-kr260-mv-defect-detect: executable-not-elf-or-script opt/xlnx-app-kr260-mv-defect-detect/bin/alloc_table.bin
W: xlnx-app-kr260-mv-defect-detect: executable-not-elf-or-script opt/xlnx-app-kr260-mv-defect-detect/bin/eeprom.bin

Thanks!
LM

**Comment by karthikxil** [comment]
In the next commit i will remove the executable permission to eeprom.bin & alloc_table.bin
